// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAn_A34i_NPSvFDrzavKBlpDS7-1kHCQE',
    appId: '1:447801848332:web:0326b568a0810642bdb429',
    messagingSenderId: '447801848332',
    projectId: 'laundry-one-45675',
    authDomain: 'laundry-one-45675.firebaseapp.com',
    storageBucket: 'laundry-one-45675.firebasestorage.app',
    measurementId: 'G-FSF0B00ZV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6GrUtGY_LaszNk6ORD7SXu_1J1o65pFE',
    appId: '1:447801848332:android:f4abe34626b439b0bdb429',
    messagingSenderId: '447801848332',
    projectId: 'laundry-one-45675',
    storageBucket: 'laundry-one-45675.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACyYOVXQt7ulprOZXhBuwyg5bzWf3-RE4',
    appId: '1:447801848332:ios:6e9af14de5f4b676bdb429',
    messagingSenderId: '447801848332',
    projectId: 'laundry-one-45675',
    storageBucket: 'laundry-one-45675.firebasestorage.app',
    iosBundleId: 'com.example.laundryOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACyYOVXQt7ulprOZXhBuwyg5bzWf3-RE4',
    appId: '1:447801848332:ios:6e9af14de5f4b676bdb429',
    messagingSenderId: '447801848332',
    projectId: 'laundry-one-45675',
    storageBucket: 'laundry-one-45675.firebasestorage.app',
    iosBundleId: 'com.example.laundryOne',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAn_A34i_NPSvFDrzavKBlpDS7-1kHCQE',
    appId: '1:447801848332:web:df08b47908269702bdb429',
    messagingSenderId: '447801848332',
    projectId: 'laundry-one-45675',
    authDomain: 'laundry-one-45675.firebaseapp.com',
    storageBucket: 'laundry-one-45675.firebasestorage.app',
    measurementId: 'G-FW8641D7V5',
  );
}
